In [3]:
import numpy as np

# Question 1

In [5]:
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2

In [8]:
l=[]
for i in range(1,6):
    a=int(input("Enter an element: "))
    l.append(a)
print(l)
l1=[]
for j in range(1,6):
    b=int(input("Enter an element: "))
    l1.append(b)
print(l1)

Enter an element: 1
Enter an element: 2
Enter an element: 3
Enter an element: 4
Enter an element: 5
[1, 2, 3, 4, 5]
Enter an element: 6
Enter an element: 7
Enter an element: 8
Enter an element: 9
Enter an element: 0
[6, 7, 8, 9, 0]


In [17]:
arr = np.array(l)
arr1 = np.array(l1)
print(arr)
print("")
print(arr1)

[1 2 3 4 5]

[6 7 8 9 0]


In [19]:
arr2= np.concatenate((arr,arr1))
print(arr2)


[1 2 3 4 5 6 7 8 9 0]


In [20]:
arr3 = np.sort(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


# Question 3

In [22]:
ar = np.array([[1,2,3], [4,5,6]])
print("dimensions: ", ar.ndim)
print("size: ", ar.size)

dimensions:  2
size:  6


# Question 4

In [24]:
arr= np.arange(1,11)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [27]:
aa= arr[:,np.newaxis]
print(aa)
print(aa.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
(10, 1)


# Question 5 

In [29]:
aa= np.array([[1,2,3],[4,5,6],[7,8,9]])
aaa = np.array([[3,4,5],[6,1,9],[8,7,0]])
b= np.vstack((aa,aaa))
c= np.hstack((aa,aaa))
print("Vertical: ", b)
print("Horizontal: ",c)

Vertical:  [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 4 5]
 [6 1 9]
 [8 7 0]]
Horizontal:  [[1 2 3 3 4 5]
 [4 5 6 6 1 9]
 [7 8 9 8 7 0]]


# Question 6